# Parámetros del vehículo quadrotor x500
vehicle:
  base_model: x500             # referencia al directorio de modelos PX4 (x500/model.sdf)
  mass: 1.5                    

  inertia:
    ixx: 0.029125
    iyy: 0.029125
    izz: 0.055225

  rotors:
    motor_constant: 8.54858e-06
    moment_constant: 0.016
    max_rot_velocity: 1000.0   
    time_constant_up: 0.0125
    time_constant_down: 0.025
    drag_coefficient: 8.06428e-05
    rolling_moment_coefficient: 1.0e-06
    velocity_slowdown_sim: 10

  px4_airframe_id: 4001        